/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cola.prioridad.bicola;

import static javax.swing.JOptionPane.*;

/**
 *
 * @author luisa
 */
public class Ventana extends javax.swing.JFrame {
    PrioridadBicola Cola;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        txtTam.requestFocus();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        txtDato = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNewIni = new javax.swing.JButton();
        btnNewFin = new javax.swing.JButton();
        btnDeleteIni = new javax.swing.JButton();
        btnDeleteFin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        txtINIFIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cola Prioridad Bicola");

        txtTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTamKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Tamaño de Bicola:");

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        txtDato.setEnabled(false);

        txtNivel.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Dato (char)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Nivel (1 a 3)");

        btnNewIni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewIni.setText("Insertar (Ini)");
        btnNewIni.setEnabled(false);
        btnNewIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewIniActionPerformed(evt);
            }
        });

        btnNewFin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewFin.setText("Insertar (Fin)");
        btnNewFin.setEnabled(false);
        btnNewFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFinActionPerformed(evt);
            }
        });

        btnDeleteIni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteIni.setForeground(new java.awt.Color(230, 0, 0));
        btnDeleteIni.setText("Eliminar (Ini)");
        btnDeleteIni.setEnabled(false);
        btnDeleteIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIniActionPerformed(evt);
            }
        });

        btnDeleteFin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteFin.setForeground(new java.awt.Color(230, 0, 0));
        btnDeleteFin.setText("Eliminar (Fin)");
        btnDeleteFin.setEnabled(false);
        btnDeleteFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFinActionPerformed(evt);
            }
        });

        txtDatos.setEditable(false);
        txtDatos.setColumns(20);
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        txtINIFIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnCrear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNivel)
                            .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnNewIni)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDeleteIni)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnDeleteFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNewFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtINIFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(txtINIFIN)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewIni)
                            .addComponent(btnNewFin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteIni)
                            .addComponent(btnDeleteFin))
                        .addGap(0, 38, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try{
            if(txtTam.getText().equals(""))showMessageDialog(null,"¡Introduzca el tamaño de la cola!");
            else {
                Cola = new PrioridadBicola(Integer.parseInt(txtTam.getText()));
                txtDatos.setText("");
                activar();
                txtDato.requestFocus();
            }
        }catch(NumberFormatException e){
            showMessageDialog(null,"¡Introduzca solo numeros en el tamaño de la cola!");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtTamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER)btnCrear.doClick();
    }//GEN-LAST:event_txtTamKeyPressed

    private void btnNewIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewIniActionPerformed
        Insertar(0);
        txtINIFIN.setText("INI: " + Cola.ini + "     FIN: " + Cola.fin);
    }//GEN-LAST:event_btnNewIniActionPerformed

    private void btnNewFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFinActionPerformed
        Insertar(1);
        txtINIFIN.setText("INI: " + Cola.ini + "     FIN: " + Cola.fin);
    }//GEN-LAST:event_btnNewFinActionPerformed

    private void btnDeleteIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIniActionPerformed
        Eliminar(0);
        txtINIFIN.setText("INI: " + Cola.ini + "     FIN: " + Cola.fin);
    }//GEN-LAST:event_btnDeleteIniActionPerformed

    private void btnDeleteFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFinActionPerformed
        Eliminar(1);
        txtINIFIN.setText("INI: " + Cola.ini + "     FIN: " + Cola.fin);
    }//GEN-LAST:event_btnDeleteFinActionPerformed

    public void Insertar(int a){
        try{
            if((txtDato.getText().equals("") || txtDato.getText().length()>1))showMessageDialog(null,"¡Asegurese de Introducir bien el dato!");
            else if((Integer.parseInt(txtNivel.getText())< 1 || Integer.parseInt(txtNivel.getText()) > 3)||(txtNivel.getText().equals("")))
                showMessageDialog(null,"¡Asegurese de Introducir bien el nivel (entre 1 y 3)!");
            else{
                boolean res = (a == 0)? Cola.newIniDato(txtDato.getText().charAt(0), Integer.parseInt(txtNivel.getText())) : Cola.newFinDato(txtDato.getText().charAt(0), Integer.parseInt(txtNivel.getText()));
                if(!res)showMessageDialog(null,"¡Error al introducir los datos " + ((a == 0)? "(Cola llena o INI lleno)!" : "(Cola llena)!"));
                else txtDatos.setText(Cola.toString());
            }
        }catch(NumberFormatException e){
            showMessageDialog(null,"¡Asegurese de Introducir solo numeros en el nivel!");
        }
    }
    
    public void Eliminar(int a){
            boolean res = a==0? Cola.DeleteIniDato() : Cola.DeleteFinDato();
            if(!res)showMessageDialog(null,"¡Error al Eliminar los datos (Cola vacía!");
            else txtDatos.setText(Cola.toString());
    }
    
    public void activar(){
        txtDato.setEnabled(true);
        txtNivel.setEnabled(true);
        btnNewIni.setEnabled(true);
        btnNewFin.setEnabled(true);
        btnDeleteIni.setEnabled(true);
        btnDeleteFin.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDeleteFin;
    private javax.swing.JButton btnDeleteIni;
    private javax.swing.JButton btnNewFin;
    private javax.swing.JButton btnNewIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextArea txtDatos;
    private javax.swing.JLabel txtINIFIN;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
